[colors]
foreground = "#575279"
background = "#faf4ed"

cursor_bg = "#9893a5"
cursor_border = "#9893a5"
cursor_fg = "#575279"

selection_bg = "#f2e9e1"
selection_fg = "#575279"

ansi = ["#f2e9de", "#b4637a", "#286983", "#ea9d34", "#56949f", "#907aa9", "#d7827e", "#575279"]
brights = ["#6e6a86", "#b4637a", "#286983", "#ea9d34", "#56949f", "#907aa9", "#d7827e", "#575279"]

[colors.tab_bar]
background = "#faf4ed"
inactive_tab_edge = "#faf4ed"

[colors.tab_bar.active_tab]
fg_color = "#faf4ed"
bg_color = "#286983"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#575279"
bg_color = "#f2e9e1"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#575279"
bg_color = "#9893a5"

[colors.tab_bar.new_tab]
fg_color = "#575279"
bg_color = "#f2e9e1"

[colors.tab_bar.new_tab_hover]
fg_color = "#575279"
bg_color = "#9893a5"
intensity = "Bold"
