# rose-pine

[colors]
foreground = "#e0def4"
background = "#191724"

cursor_bg = "#524f67"
cursor_border = "#524f67"
cursor_fg = "#e0def4"

selection_bg = "#2a283e"
selection_fg = "#e0def4"

ansi = ["#26233a", "#eb6f92", "#31748f", "#f6c177", "#9ccfd8", "#c4a7e7", "#ebbcba", "#e0def4"]
brights = ["#6e6a86", "#eb6f92", "#31748f", "#f6c177", "#9ccfd8", "#c4a7e7", "#ebbcba", "#e0def4"]

[colors.tab_bar]
background = "#191724"
inactive_tab_edge = "#191724"

[colors.tab_bar.active_tab]
fg_color = "#191724"
bg_color = "#31748f"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#e0def4"
bg_color = "#2a283e"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#e0def4"
bg_color = "#2a283e"

[colors.tab_bar.new_tab]
fg_color = "#e0def4"
bg_color = "#2a283e"

[colors.tab_bar.new_tab_hover]
fg_color = "#e0def4"
bg_color = "#2a283e"
intensity = "Bold"
